version: '3.8'

services:
  effecti-front:
    image: luansmeloo/vue-effecti-test
    container_name: effecti-front
    ports:
      - "8082:80"
    networks:
      - effecti

  effecti:
    image: luansmeloo/spring-effecti-test
    container_name: effecti
    ports:
      - "8081:8080"
    networks:
      - effecti

networks:
  effecti:
    driver: bridge